travis: Add a test that code files don't have the exec bit set
C source code and header files shouldn't be executable.
This is a problem that already occurred pretty often in the past and was
e.g. fixed in 5d8c5ae, be95415, and 8352ab9. Therefore it seems like a
good idea to add a CI check to prevent this issue from reappearing
(probably mostly accidents due to wrong Git configurations, etc.).

Signed-off-by: Michael Weiss <dev.primeos@gmail.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -28,7 +28,7 @@ before_install:
   - sudo apt-get install -y autoconf
   - sudo apt-get install -y automake
   - sudo apt-get install -y libtool
-  - sudo apt-get install -y m4 
+  - sudo apt-get install -y m4
   - sudo apt-get install -y lcov
   - sudo apt-get install -y perl
   - sudo apt-get install -y pkg-config
@@ -56,6 +56,12 @@ script:
       then
         echo "Don't build on coverty_scan branch.";
         exit 0;
+    fi
+  - if [[ -n "$(find -name '*.[ch]' -executable)" ]];
+      then
+        echo "Error, a source code file(s) has the execute bit set:" >&2;
+        find -name '*.[ch]' -executable;
+        exit 1;
     fi
   - ./autogen.sh
   - ./configure --prefix=/usr
